api/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'api'

urlpatterns = [
    path('user/get-user',get_user,name='get_user'),
    path('product/get-product',ManageProduct.as_view(),name='get_product'),
    path('product/create-product',func_product,name='create_product'),
    ]

product/urls.py
from django.urls import path
from .views import *
from shop_app import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'products'

urlpatterns = [
    path('', index,name='index'),
    path('cart/', view_cart,name='cart'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf import settings
from django.conf.urls.static import static
from shop_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("users.urls", namespace="users")),
    path('product/',include("product.urls", namespace="product")),
    path('api/',include("api.urls", namespace="api")),
    path('shop/', include("shop_app.urls"), name='shop'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.utils import timezone
from users.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length =70,verbose_name ="نام دسته بندی ")
    image = models.ImageField(upload_to='image/',verbose_name='عکس', default='media/imgae/default.png', blank=True, null=True)

    
    
    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        
        
class ProductInfo(models.Model):
    STATUS_CHOICES = [
        ('in_stock', 'موجود'),
        ('out_of_stock', 'ناموجود'),
        ('coming_soon', 'به زودی'),
    ]
    name = models.CharField(max_length=70, verbose_name="نام")
    description = models.TextField(verbose_name="توضیحات")
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    modified = models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')
    price = models.BigIntegerField(verbose_name='قیمت', default=0)
    pr_date = models.DateTimeField(default=timezone.now, verbose_name='تاریخ تولید')
    exp_date = models.DateTimeField(default=timezone.now, verbose_name="تاریخ انقضا")
    brand = models.CharField(max_length=50, null=True, blank=True, verbose_name="برند")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته‌بندی', related_name='products', default=1)
    image = models.ImageField(upload_to='image/', verbose_name='عکس', default='media/image/default.png', blank=True, null=True)
    purchase_count = models.PositiveIntegerField(default=0, verbose_name="تعداد خرید")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='in_stock', verbose_name='وضعیت')

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

# class ProductLike(models.Model):
#     pass



class ProductComment(models.Model):
    product = models.ForeignKey('ProductInfo', on_delete=models.CASCADE, related_name='comments', verbose_name="محصول", default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر", default=1)
    comment = models.TextField(verbose_name="نظر", default="بدون نظر")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="تاریخ ایجاد")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی")

    class Meta:
        ordering = ['-created_at']
        verbose_name = "نظر محصول"
        verbose_name_plural = "نظرات محصولات"

    def __str__(self):
        return f'نظر توسط {self.user.username} برای {self.product.name}'

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductInfo, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'product')

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import ProductInfo, Category, Favorite
from .serializers import ProductSerializer

# Create your views here.
def index(request):
    product_tmp = ProductInfo.objects.all()
    products = ProductSerializer(product_tmp, many = True)
    if request.method == "POST":
        data = request.POST.get("product")
        print("*******",data)
        pr = request.session.get("selected")
        if pr is None:
            pr=[]
        pr.append(data)
        request.session["selected"] = pr
        print(pr)
    
    rt = render(request=request,template_name="index.html",context={"products":products.data})
    # rt.set_cookie("selected",pr)
    return rt

def view_cart(request):
    if request.method == "POST":
        data = request.POST.get("product")
        if data:
            pr = request.session.get("selected", [])
            
            if data in pr:
                pr.remove(data)
                request.session["selected"] = pr
            else:
                print(f"محصول {data} در لیست موجود نیست.")
    
    sessions = request.session.get("selected", [])
    
    products = ProductInfo.objects.filter(id__in=sessions)
    
    total_price = sum([item.price for item in products])
    
    return render(request, template_name="cart.html", context={
        "products": products,
        "total_price": total_price
    })
    
def calculate_total_price(request):
    sessions = request.session.get("selected", [])
    products = ProductInfo.objects.filter(id__in=sessions)
    total_price = sum([item.price for item in products])
    return total_price
    
def purchase_product(request, product_id):
    product = get_object_or_404(ProductInfo, id=product_id)
    product.purchase_count += 1
    product.save()
    return redirect('shop_app:home')  




def add_to_favorite(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(ProductInfo, id=product_id)
        favorite, created = Favorite.objects.get_or_create(user=request.user, product=product)
        if not created:
            favorite.delete() 
        print(favorite)
        return redirect('shop_app:home')  
    
    
def get_cart_and_liked_products(request):
    selected_ids = request.session.get("selected", [])
    
    products_in_cart = ProductInfo.objects.filter(id__in=selected_ids).distinct()
    products_liked = ProductInfo.objects.filter(id__in=selected_ids).exclude(id__in=selected_ids).distinct()

    return products_in_cart, products_liked

product/templates/cart.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>products</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  </head>
  <body>
    {% if products|length == 0 %}
      <h1>محصولی در سبد خرید موجود نیست</h1>
    {% else %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">نام محصول</th>
            <th scope="col">قیمت</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <td>
                <p>{{ product.name }}</p>
              </td>
              <td>
                <p>{{ product.price }}</p>
              </td>
              <td>
                <form action="" method="post">
                  {% csrf_token %}
                  <input name="product" id="product" type="text" value="{{ product.id }}" hidden />
                  <input type="submit" class="btn btn-outline-danger" value="حذف" />
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <h2>قیمت کل: {{ total_price }}</h2>
    {% endif %}
  </body>
</html>

product/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>products</title>
  </head>
  <body>
    <a href="{% url 'products:cart' %}" target="_blank">مشاهده سبد خرید</a>
    {% for pro in products %}
      <h2>{{ pro.name }}</h2>
      <form action="" method="post">
        {% csrf_token %}
        <input name="product" id="product" type="text" value="{{ pro.id }}" hidden />
        <input type="submit" value="افزودن به سبد خرید" />
        <input type="submit" value="حذف" />
      </form>
    {% endfor %}
  </body>
</html>