api/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'api'

urlpatterns = [
    path('user/get-user',get_user,name='get_user'),
    path('product/get-product',ManageProduct.as_view(),name='get_product'),
    path('product/create-product',func_product,name='create_product'),
    ]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf import settings
from django.conf.urls.static import static
from shop_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("users.urls", namespace="users")),
    path('product/',include("product.urls", namespace="product")),
    path('api/',include("api.urls", namespace="api")),
    path('shop/', include("shop_app.urls"), name='shop'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *

app_name='shop_app'

urlpatterns=[
    path('home/', home, name='home'),
    path('explore/', explore, name='explore'),
    path('details/<int:id>/', details, name='details'),
    path('create/', create, name='create'),
    path('author/', author, name='author'),
    path('users/', include('users.urls')),

    

    
]

users/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'users'

urlpatterns = [
    path('', index,name='index'),
    path('dashboard/',dashboard_view,name= 'dashboard'),
    path('login/',otp_login,name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',signup,name='signup'),
    path('login/verify',verify_code,name='verify'),
    path('login/verify/success/', success_page, name='success_page'),
    # path('success/', success_page, name='success_page'),  
    path('profile/', profile, name='profile'),
    # path('shop/', include('shop_app.urls')),
]

shop_app/models.py
from django.db import models

# Create your models here.

shop_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Category, ProductInfo, ProductComment
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from product.serializers import ProductSerializer



def home(request):
    if request.method == "POST":
        product_id = request.POST.get("product")
        print("Received product_id:", product_id)
        
        if not request.user.is_authenticated:
            return redirect('users:signup')

        if product_id:
            product_id = str(product_id)
            liked = request.session.get("selected", [])
            liked = [item for item in liked if item]
            print("Current liked list:", liked)

            if product_id not in liked:
                liked.append(product_id)
                request.session["selected"] = liked
                print("Product added:", liked)
            else:
                print("Product already in liked list")
        else:
            print("Invalid product ID")

    category = Category.objects.all()
    selected_category_id = request.GET.get('category_id', None)

    if selected_category_id:
        products = ProductInfo.objects.filter(category_id=selected_category_id, purchase_count__gt=100)
    else:
        products = ProductInfo.objects.filter(purchase_count__gt=100)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        products_data = list(products.values('id', 'name', 'image', 'description', 'price', 'brand'))
        return JsonResponse({'products': products_data})

    selected_ids = request.session.get("selected", [])
    products_in_cart = ProductInfo.objects.filter(id__in=selected_ids).distinct()
    products_liked = ProductInfo.objects.filter(id__in=selected_ids).exclude(id__in=selected_ids).distinct()

    products_selected = ProductSerializer(products, many=True)
    products_in_cart_serialized = ProductSerializer(products_in_cart, many=True)
    products_liked_serialized = ProductSerializer(products_liked, many=True)

    context = {
        "category": category,
        "products": products,
        "products_selected": products_selected.data,
        "products_in_cart": products_in_cart_serialized.data,
        "products_liked": products_liked_serialized.data,
    }

    return render(request, "shop/home.html", context)



def create(request):
    return render(request=request, template_name="shop/create.html", context={})

def author(request):
    return render(request=request, template_name="shop/author.html", context={})

def explore(request):
    if request.method == 'POST':
        products = ProductInfo.objects.all()
    else:
        products = ProductInfo.objects.all()

    return render(request, "shop/explore.html", {"products": products})




def details(request, id):
    product = get_object_or_404(ProductInfo, id=id)
    other_products = ProductInfo.objects.all().exclude(id=product.id)[:6]
    similar_products = ProductInfo.objects.filter(category=product.category).exclude(id=product.id)[:6]

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_text = request.POST.get('comment', '')
            if comment_text:
                ProductComment.objects.create(
                    product=product,
                    user=request.user,
                    comment=comment_text
                )
            return redirect('shop_app:details', id=id)  

    return render(request, 'shop/details.html', {
        'product': product,
        'similar_products': similar_products,
        'other_products': other_products
    })

shop_app/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        h1, h2, h3, h4, h5, h6 {
            margin-top: 0px;
            margin-bottom: 0px;
            color: #fff  !important;
            font-weight: 700;
          }
    </style>
    
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>
        onlinde-
        {% block title %}
        {% endblock %}
    </title>
    <!-- بارگذاری CSS‌ها در فایل هدر -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-liberty-market.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'base/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'base/footer.html' %}
    {% block extra_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/isotope.min.js' %}"></script>
    <script src="{% static 'js/owl-carousel.js' %}"></script>
    <script src="{% static 'js/tabs.js' %}"></script>
    <script src="{% static 'js/popup.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% endblock %}
</body>
</html>

shop_app/templates/base/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



 

</head>
<body>
    <footer>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
      </svg>      </footer>
    
    
    
      {% block footer %}
      {% endblock %}
</body>
</html>

shop_app/templates/base/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



   
    <title>
    </title>

</head>
<body>
    <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                    
                        <ul class="nav">
                            <li><a href="{% url 'shop_app:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a></li>
                            <li><a href="{% url 'shop_app:explore' %}" class="{% if request.resolver_match.url_name == 'explore' %}active{% endif %}">Explore</a></li>
                          
                            <li>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'users:logout' %}">Logout</a>
                                {% else %}
                                    <a href="{% url 'users:login' %}" class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}">Login</a>
                                {% endif %}
                            </li>
                            <li><a href="{% url 'users:signup' %}" class="{% if request.resolver_match.url_name == 'signup' %}active{% endif %}">Signup</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="{% if request.resolver_match.url_name == 'profile' %}active{% endif %}">Profile</a></li>
                        {% endif %} 
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    
    
      {% block header%}
      {% endblock %}
</body>
</html>