api/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'api'

urlpatterns = [
    path('user/get-user',get_user,name='get_user'),
    path('product/get-product',ManageProduct.as_view(),name='get_product'),
    path('product/create-product',func_product,name='create_product'),
    ]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf import settings
from django.conf.urls.static import static
from shop_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("users.urls", namespace="users")),
    path('product/',include("product.urls", namespace="product")),
    path('api/',include("api.urls", namespace="api")),
    path('shop/', include("shop_app.urls"), name='shop'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *

app_name='shop_app'

urlpatterns=[
    path('home/', home, name='home'),
    path('explore/', explore, name='explore'),
    path('details/<int:id>/', details, name='details'),
    path('create/', create, name='create'),
    path('author/', author, name='author'),
    path('users/', include('users.urls')),

    

    
]

users/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'users'

urlpatterns = [
    path('', index,name='index'),
    path('dashboard/',dashboard_view,name= 'dashboard'),
    path('login/',otp_login,name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',signup,name='signup'),
    path('login/verify',verify_code,name='verify'),
    path('login/verify/success/', success_page, name='success_page'),
    # path('success/', success_page, name='success_page'),  
    path('profile/', profile, name='profile'),
    # path('shop/', include('shop_app.urls')),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "AD","Admin"
        SHOP_ADMIN = "SH","ShopAdmin"
        CUSTOMER = "CU","Customer"

    national_code = models.CharField(max_length=50, null=True, blank=True, verbose_name="کد ملی")
    phone = models.CharField(max_length=50, null=True, blank=True, unique=True, verbose_name="شماره تماس")
    address = models.TextField(null=True, blank=True, verbose_name="آدرس")
    last_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='آخرین آدرس آی پی')
    role = models.CharField(max_length=2, choices=Role.choices, default=Role.CUSTOMER, verbose_name='نقش')

users/forms.py
from django import forms
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='username ', max_length=20)
    password = forms.CharField(label='password', max_length=20, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'inputregister'})
        self.fields['password'].widget.attrs.update({'class': 'inputregister'})


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'national_code']
        labels = {
            'username': ' username',
            'password': 'password ',
            'first_name': 'first name',
            'last_name': 'last_name ',
            'national_code': ' national code',

            }
        help_texts = {
            'username': None,  
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'inputregister'})

class OtpForm(forms.Form):
    phone = forms.CharField(label="شماره تماس", max_length=11)
    

class VerifyCode(forms.Form):
    code = forms.CharField(label="کد تایید", max_length=11)

users/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from .forms import LoginForm , SignUpForm,OtpForm,VerifyCode
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .models import User
from .serializers import UserSerializer
from rest_framework.decorators import api_view,permission_classes
from rest_framework.response import Response
from rest_framework import status
from random import randint
import requests
from shop import settings
from kavenegar import *
from django.contrib import messages
from product.views import calculate_total_price, get_cart_and_liked_products
# Create your views here.

def index(request):
    request.session['admin2'] = "admin khers"
    res = HttpResponse(request,"Set Cookie")
    res.set_cookie("admin2","admin2 hastam")
    return res
    # return render(request=request,template_name='user/index.html')

@login_required
def dashboard_view(request):
    print("kharkose")
    return render(request=request,template_name='user/dashboard.html')

def signup(request):
    signup_form = SignUpForm()
    login_form = LoginForm()  
    
    if request.method == "POST":
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save(commit=False)
            user.set_password(signup_form.cleaned_data['password'])
            user.is_staff = True
            user.save()
    
    return render(request, 'user/signup.html', context={'signup_form': signup_form, 'login_form': login_form})



# def login_user(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request=request,username = cd['username'],password = cd['password'])
#             if user is None:
#                 return HttpResponse(content='نام کاربری یا رمز عبور اشتباه است')
#             else:
#                 login(request=request,user=user)
#                 return render(request=request,template_name='user/inde.html')
#         else:
#             pass
#     else:
#         form = LoginForm()
#     return render(request=request,template_name='user/login.html',context={'form':form})

# def logout_user(request):
#     try:
#         user = User.objects.get(id = request.user.id)
#     except User.DoesNotExist:
#         print('yrdsssss')
#         return redirect('users:login')
#     logout(request=request)
#     print('yrdsssss2')
#     return render(request=request,template_name='user/inde.html')

def send_otp(phone_number):
    code = randint(1000,9999)
    # api_key = settings.API_KEY_SMS
    # message = f'your code is {code}'
    # # api = KavenegarAPI(api_key)
    # # data= {
    # #     "receptor": phone_number,
    # #     "message":message
    # # }
    # # res = api.sms_send(data)
    # # print("*",res)
    # url = f"https://api.kavenegar.com/v1/{api_key}/sms/send.json"
    # data= {
    #     "receptor": phone_number,
    #     "message":message,
    #     "sender":"200050066"
    # }
    # res = requests.post(url=url,data=data)
    print(code)
    return code



def otp_login(request):
    if request.method == "POST":
        form = OtpForm(request.POST)  
        if form.is_valid():
            c_data = form.cleaned_data
            try:
                user = User.objects.get(phone=c_data.get("phone"))
                code = send_otp(user.phone)
                request.session["code"] = code
                messages.success(request, "کد تأیید به شماره شما ارسال شد.")
                return redirect('users:verify')  
            except User.DoesNotExist:
                messages.error(request, "شماره وارد شده در سیستم وجود ندارد.")
        else:
            messages.error(request, "فرم نامعتبر است. لطفاً شماره تلفن خود را به درستی وارد کنید.")
    else:
        form = OtpForm()  

    return render(request, "registration/login.html", {"form": form})


def verify_code(request):
    if request.method == "POST":
        form_data = VerifyCode(request.POST)
        if form_data.is_valid():
            c_data = form_data.cleaned_data
            code = str(request.session.get("code"))
            user_phone = c_data.get("phone")
            input_code = str(c_data.get("code"))

            if code == input_code:
                users = User.objects.filter(phone=user_phone)
                if users.count() == 1:
                    user = users.first()
                    login(request, user)
                    messages.success(request, "خوش آمدید!")
                    return redirect('users:profile')  
                elif users.count() > 1:
                    messages.error(request, "چندین کاربر با این شماره تلفن وجود دارد.")
                    return render(request, "registration/verify.html", {"form": form_data})
                else:
                    messages.error(request, "کاربر با این شماره تلفن یافت نشد.")
                    return render(request, "registration/verify.html", {"form": form_data})
            else:
                messages.error(request, "کد وارد شده صحیح نمی‌باشد.")
                return render(request, "registration/verify.html", {"form": form_data})
    else:
        form = VerifyCode()
    return render(request, "registration/verify.html", {"form": form})




def success_page(request):
    return render(request, 'registration/success_page.html')

@login_required
def profile(request):
    products_in_cart, products_liked = get_cart_and_liked_products(request)

    users = User.objects.all()

    total_price = calculate_total_price(request)

    context = {
        'users': users,
        'total_price': total_price,
        'products_in_cart': products_in_cart,
        'products_liked': products_liked,
    }

    return render(request, 'user/profile.html', context)

users/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        h1, h2, h3, h4, h5, h6 {
            margin-top: 0px;
            margin-bottom: 0px;
            color: #fff  !important;
            font-weight: 700;
          }
    </style>
    
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>
        
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-liberty-market.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% include 'base/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'base/footer.html' %}
    {% block extra_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/isotope.min.js' %}"></script>
    <script src="{% static 'js/owl-carousel.js' %}"></script>
    <script src="{% static 'js/tabs.js' %}"></script>
    <script src="{% static 'js/popup.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% endblock %}
</body>
</html>

users/templates/base/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



 

</head>
<body>
    <footer>
      <a href="https://github.com/RoxanaNegaresh">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
      </svg>
    </a>
    <a href="https://www.linkedin.com/in/roxana-negaresh-247a7a318/">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
      </svg>
    </a>
    <a href="https://x.com/Its_Roxanax?s=09">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334q.002-.211-.006-.422A6.7 6.7 0 0 0 16 3.542a6.7 6.7 0 0 1-1.889.518 3.3 3.3 0 0 0 1.447-1.817 6.5 6.5 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.32 9.32 0 0 1-6.767-3.429 3.29 3.29 0 0 0 1.018 4.382A3.3 3.3 0 0 1 .64 6.575v.045a3.29 3.29 0 0 0 2.632 3.218 3.2 3.2 0 0 1-.865.115 3 3 0 0 1-.614-.057 3.28 3.28 0 0 0 3.067 2.277A6.6 6.6 0 0 1 .78 13.58a6 6 0 0 1-.78-.045A9.34 9.34 0 0 0 5.026 15"/>
      </svg>
    </a>
    <a href="https://t.me/WellMeetAgainSoon">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.287 5.906q-1.168.486-4.666 2.01-.567.225-.595.442c-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294q.39.01.868-.32 3.269-2.206 3.374-2.23c.05-.012.12-.026.166.016s.042.12.037.141c-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8 8 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629q.14.092.27.187c.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.4 1.4 0 0 0-.013-.315.34.34 0 0 0-.114-.217.53.53 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09"/>
      </svg>
    </a>
    
      </footer>
    
    
    
      {% block footer %}
      {% endblock %}
</body>
</html>

users/templates/base/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



   
    <title>
    </title>

</head>
<body>
    <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <a href="{% url 'shop_app:home' %}" class="logo">
                            <img src="{% static 'assets/images/smth' %}" alt="">
                        </a>
                  
                        <ul class="nav">
                            <form method="post">

                            <li><a href="{% url 'shop_app:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a></li>
                            <li><a href="{% url 'shop_app:explore' %}" class="{% if request.resolver_match.url_name == 'explore' %}active{% endif %}">Explore</a></li>
                     
                          
                                <li><a href="{% url 'users:signup' %}" class="{% if request.resolver_match.url_name == 'signup' %}active{% endif %}">Registration</a></li>
                                <li>

                                    {% if user.is_authenticated %}
                                        <a href="{% url 'users:logout' %}">Logout</a>
                                    {% else %}
                                        <a href="{% url 'users:login' %}" class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}">Login</a>
                                    {% endif %}
                                </form>
    
                                </li>
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'users:profile' %}" class="{% if request.resolver_match.url_name == 'profile' %}active{% endif %}">Profile</a></li>
                            {% endif %} 
                            </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    
    
      {% block header%}
      {% endblock %}
</body>
</html>