api/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'api'

urlpatterns = [
    path('user/get-user',get_user,name='get_user'),
    path('product/get-product',ManageProduct.as_view(),name='get_product'),
    path('product/create-product',func_product,name='create_product'),
    ]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf import settings
from django.conf.urls.static import static
from shop_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("users.urls", namespace="users")),
    path('product/',include("product.urls", namespace="product")),
    path('api/',include("api.urls", namespace="api")),
    path('shop/', include("shop_app.urls"), name='shop'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *

app_name='shop_app'

urlpatterns=[
    path('home/', home, name='home'),
    path('explore/', explore, name='explore'),
    path('details/<int:id>/', details, name='details'),
    path('create/', create, name='create'),
    path('author/', author, name='author'),
    path('users/', include('users.urls')),

    

    
]

product/models.py
from django.db import models
from django.utils import timezone
from users.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length =70,verbose_name ="نام دسته بندی ")
    image = models.ImageField(upload_to='image/',verbose_name='عکس', default='media/imgae/default.png', blank=True, null=True)

    
    
    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        
        
class ProductInfo(models.Model):
    STATUS_CHOICES = [
        ('in_stock', 'موجود'),
        ('out_of_stock', 'ناموجود'),
        ('coming_soon', 'به زودی'),
    ]
    name = models.CharField(max_length=70, verbose_name="نام")
    description = models.TextField(verbose_name="توضیحات")
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    modified = models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')
    price = models.BigIntegerField(verbose_name='قیمت', default=0)
    pr_date = models.DateTimeField(default=timezone.now, verbose_name='تاریخ تولید')
    exp_date = models.DateTimeField(default=timezone.now, verbose_name="تاریخ انقضا")
    brand = models.CharField(max_length=50, null=True, blank=True, verbose_name="برند")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته‌بندی', related_name='products', default=1)
    image = models.ImageField(upload_to='image/', verbose_name='عکس', default='media/image/default.png', blank=True, null=True)
    purchase_count = models.PositiveIntegerField(default=0, verbose_name="تعداد خرید")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='in_stock', verbose_name='وضعیت')

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

# class ProductLike(models.Model):
#     pass



class ProductComment(models.Model):
    product = models.ForeignKey('ProductInfo', on_delete=models.CASCADE, related_name='comments', verbose_name="محصول", default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر", default=1)
    comment = models.TextField(verbose_name="نظر", default="بدون نظر")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="تاریخ ایجاد")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی")

    class Meta:
        ordering = ['-created_at']
        verbose_name = "نظر محصول"
        verbose_name_plural = "نظرات محصولات"

    def __str__(self):
        return f'نظر توسط {self.user.username} برای {self.product.name}'

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductInfo, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'product')

shop_app/models.py
from django.db import models

# Create your models here.

shop_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Category, ProductInfo, ProductComment
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from product.serializers import ProductSerializer



def home(request):
    if request.method == "POST":
        product_id = request.POST.get("product")
        print("Received product_id:", product_id)
        
        if not request.user.is_authenticated:
            return redirect('users:signup')

        if product_id:
            product_id = str(product_id)
            liked = request.session.get("selected", [])
            liked = [item for item in liked if item]
            print("Current liked list:", liked)

            if product_id not in liked:
                liked.append(product_id)
                request.session["selected"] = liked
                print("Product added:", liked)
            else:
                print("Product already in liked list")
        else:
            print("Invalid product ID")

    category = Category.objects.all()
    selected_category_id = request.GET.get('category_id', None)

    if selected_category_id:
        products = ProductInfo.objects.filter(category_id=selected_category_id, purchase_count__gt=100)
    else:
        products = ProductInfo.objects.filter(purchase_count__gt=100)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        products_data = list(products.values('id', 'name', 'image', 'description', 'price', 'brand'))
        return JsonResponse({'products': products_data})

    selected_ids = request.session.get("selected", [])
    products_in_cart = ProductInfo.objects.filter(id__in=selected_ids).distinct()
    products_liked = ProductInfo.objects.filter(id__in=selected_ids).exclude(id__in=selected_ids).distinct()

    products_selected = ProductSerializer(products, many=True)
    products_in_cart_serialized = ProductSerializer(products_in_cart, many=True)
    products_liked_serialized = ProductSerializer(products_liked, many=True)

    context = {
        "category": category,
        "products": products,
        "products_selected": products_selected.data,
        "products_in_cart": products_in_cart_serialized.data,
        "products_liked": products_liked_serialized.data,
    }

    return render(request, "shop/home.html", context)



def create(request):
    return render(request=request, template_name="shop/create.html", context={})

def author(request):
    return render(request=request, template_name="shop/author.html", context={})

def explore(request):
    if request.method == 'POST':
        products = ProductInfo.objects.all()
    else:
        products = ProductInfo.objects.all()

    return render(request, "shop/explore.html", {"products": products})




def details(request, id):
    product = get_object_or_404(ProductInfo, id=id)
    other_products = ProductInfo.objects.all().exclude(id=product.id)[:6]
    similar_products = ProductInfo.objects.filter(category=product.category).exclude(id=product.id)[:6]

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_text = request.POST.get('comment', '')
            if comment_text:
                ProductComment.objects.create(
                    product=product,
                    user=request.user,
                    comment=comment_text
                )
            return redirect('shop_app:details', id=id)  

    return render(request, 'shop/details.html', {
        'product': product,
        'similar_products': similar_products,
        'other_products': other_products
    })

shop_app/templates/shop/details.html
{% extends 'base/base.html' %}  

{% block title %}
  daitasl
{% endblock %}

{% load static %}

{% block content %}

 <div id="js-preloader" class="js-preloader">
  <div class="preloader-inner">
    <span class="dot"></span>
    <div class="dots">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
</div> 
  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2>View Item Details</h2>
          <div class="buttons">
            <div class="border-button">
              <a href="{% url 'shop_app:explore' %}">Explore Our Product!</a>
            </div>
            <div class="main-button">
              <a href="https://www.youtube.com/@JeanWatts" target="_blank">Learn how to makeup!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="item-details-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>View Details <em>For Item</em> Here.</h2>
          </div>
        </div>
        <div class="col-lg-7">
          <div class="left-image">
              <img src="{{ product.image.url }}" alt="{{ product.name }}" style="border-radius: 20px;">
          </div>
        </div>
        <div class="col-lg-5 align-self-center">
          <h4>{{ product.name }}</h4>
         
          <p>{{ product.description }}</p>
          <div class="row">
              <div class="col-3">
                  <span class="bid">
                    <br><strong>${{ product.price }} </strong><br><em>{{ product.brand }}</em>
                  </span>
              </div>
              <div class="col-5">
                  <span class="ends">
                     <br><strong>{{ product.get_status_display }}</strong><br>
                  </span>
              </div>
          </div>
          <div class="container mt-5" style="display: flex; justify-content: flex-end; align-items: flex-start; padding: 20px; height: 1px; position: relative;">
            <!-- Add to Favorites Button -->
            <form action="" method="post">
                {% csrf_token %}
                <input type="hidden" name="product" value="{{ pro.id }}" />
                <button class="favorite-btn" aria-label="Add to favorites" style="background:none; border:none; padding:0; cursor:pointer;">
                    <svg viewBox="0 0 24 24" width="1.5em" height="1.5em">
                        <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41 0.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                    </svg>
                </button>
            </form>
        
            <form action="" method="post">
                {% csrf_token %}
                <input name="product" id="product" type="text" value="{{ pro.id }}" hidden />
                <button type="submit" style="background:none; border:none; padding:0; cursor:pointer;">
                    <svg class="shopping-btn" xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" viewBox="0 0 16 16">
                        <path fill="currentColor" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607L1.61 2H.5a.5.5 0 0 1-.5-.5M5 12a2 2 0 1 0 0 4a2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4a2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2a1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2a1 1 0 0 1 0-2"/>
                    </svg>
                </button>
            </form>
        </div>
        
        </div>
      </div>
      
      <div class="current-bid">
        <div class="row">
            <div class="col-lg-6">
                <div class="mini-heading">
                    {% if similar_products %}
                        <h4>Similar products</h4>
                    {% else %}
                        <h4>Other products</h4>
                    {% endif %}
                </div>
            </div>


          
                  
    
            {% if similar_products %}
                {% for similar_product in similar_products %}
                    <div class="col-lg-4 col-md-6">
                        <div class="item">
                            <div class="left-img">
                                <img src="{{ similar_product.image.url }}" alt="{{ similar_product.name }}">
                            </div>
                            <div class="right-content">
                                <h4>{{ similar_product.name }}</h4>
                                <a href="#">@{{ similar_product.author_name }}</a>
                                <div class="line-dec"></div>
                                <h6>Bid: <em>{{ similar_product.price }}</em></h6>
                                <span class="date">{{ similar_product.created_at|date:"d/m/Y, H:i" }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                {% for product in other_products %}
                    <div class="col-lg-4 col-md-6">
                        <div class="item">
                            <div class="left-img">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            </div>
                            <div class="right-content">
                                <h4>{{ product.name }}</h4>
                                <a href="#">@{{ product.author_name }}</a>
                                <div class="line-dec"></div>
                                <h6>Bid: <em>{{ product.price }}</em></h6>
                                <span class="date">{{ product.created_at|date:"d/m/Y, H:i" }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
      </div>
    </div>
  </div>


{% endblock %}

shop_app/templates/shop/explore.html
{% extends 'base/base.html' %}

{% block title %}
  Posts
{% endblock %}

{% load static %}

{% block content %}

  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div> 



  

  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Liberty NFT Market</h6>
          <h2>Discover Some Top Items</h2>
          <span>Home > <a href="{% url 'shop_app:explore' %}">Explore</a></span>
        </div>
      </div>
    </div>
    <div class="featured-explore">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="owl-features owl-carousel">
              {% for pro in products %}
              {% if pro.purchase_count > 100 %}
              <div class="item">
                <div class="thumb">
                  <img src="{{ pro.image.url }}" alt="{{ pro.name }}" style="border-radius: 20px;">
                  <div class="hover-effect">
                    <div class="content">
                      <h4 style="color: white">
                        <a href="{% url 'shop_app:details' pro.id %}" style="color: white;">
                          {{ pro.name }}
                        </a>
                      </h4>
                     
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="discover-items">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Discover Some Of Our <em>Items</em>.</h2>
          </div>
        </div>
        <div class="col-lg-7">
         
        </div>
      </div>
      <div class="col-lg-12">
        <div class="owl-collection owl-carousel">
          {% for pro in products %}
          <form action="" method="post">
            {% csrf_token %}


            <div class="item">
              <img src="{{ pro.image.url }}"> 
              <div class="down-content">
                <h4><a href="{% url 'shop_app:details' pro.id %}" style="color:white;">{{ pro.name }} </a>


                  <div class="container mt-5" style="display: flex; justify-content: flex-end; align-items: flex-start; padding: 20px; height: 1px; position: relative;">
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product" value="{{ pro.id }}" />
                        <button class="favorite-btn" aria-label="Add to favorites" name="like" style="background:none; border:none; padding:0; cursor:pointer;">
                            <svg viewBox="0 0 24 24" width="1.5em" height="1.5em">
                                <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41 0.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                            </svg>
                        </button>
                    </form>
                </div>
                
                <a>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product" value="{{ pro.id }}" />
                        <button type="submit" name="select" style="background:none; border:none; padding:0; cursor:pointer;">
                            <svg class="shopping-btn" xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" viewBox="0 0 16 16">
                                <path fill="currentColor" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607L1.61 2H.5a.5.5 0 0 1-.5-.5M5 12a2 2 0 1 0 0 4a2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4a2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2a1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2a1 1 0 0 1 0-2"/>
                            </svg>
                        </button>
                    </form>
                </a>
                



              </h4>
                <strong><span class="collection">${{ pro.price }}</strong></span>
                <span class="category">{{ pro.brand }}</span>
                <div class="main-button">
                  <a href="{% url 'shop_app:details' pro.id %}">View Item Details</a>
                </div>
              </div>
            </div>
          </form>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

{% endblock %}

shop_app/templates/shop/home.html
{% extends 'base/base.html' %}  

{% load static %}

{% block title %}
  Home
{% endblock %}



  {% block content %}

  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div> 
 
  <script>
    document.addEventListener('DOMContentLoaded', function() {
        var imageUrl = "{% static 'images/bg4.jpg' %}";
        document.querySelector('.main-banner').style.backgroundImage = 'url(' + imageUrl + ')';
    });
</script>

  <div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="header-text">
            <h6>GlowGlam</h6>
            <h2>GlowGlam: Your One-Stop Beauty Destination for Radiant Skin and Glamorous Looks</h2>
            <p>A beauty e-commerce website is an online platform that offers a wide range of beauty and skincare products, including makeup, skincare, haircare, fragrances, and beauty tools. Customers can browse through different categories, read product descriptions, reviews, and ingredient lists, and make purchases with secure payment options. Many beauty websites provide personalized recommendations, skincare routines, and virtual try-on tools to enhance the shopping experience. Additionally, these websites often feature promotions, discounts, and loyalty programs to attract and retain customers. The goal is to provide a convenient, informative, and enjoyable shopping experience for beauty enthusiasts.</p>
            <div class="buttons">
              <div class="border-button">
                <a href="{% url 'shop_app:explore' %}">Explore Our Product!</a>
              </div>
              <div class="main-button">
                <a href="https://www.youtube.com/@JeanWatts" target="_blank">Learn how to makeup!</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 offset-lg-1">
          <div class="owl-banner owl-carousel">
            <div class="item">
              <img alt="" src="{% static 'images/lip1.jpg' %}" style="width: 100%; border-radius: 40px; height: 88%;">
            </div>
            <div class="item">
              <img alt="" src="{% static 'images/lip2.jpg' %}" style="width: 100%; border-radius: 40px; height: 88%;">
            </div>
            <div class="item">
              <img alt="" src="{% static 'images/lip3.jpg' %}" style="width: 100%; border-radius: 40px; height: 88%;">
            </div>
            <div class="item">
              <img alt="" src="{% static 'images/lip4.jpg' %}" style="width: 100%; border-radius: 40px; height: 88%;">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="categories-collections">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="categories">
            <div class="row">
              <div class="col-lg-12">
        
                
              </div>
             
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="collections">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <div class="line-dec"></div>
                <h2>Explore Some Hot <em>Items</em> In Our shop.</h2>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="owl-collection owl-carousel">
                {% for pro in products %}
                <form action="" method="post">
                  {% csrf_token %}


                  <div class="item">
                    <img src="{{ pro.image.url }}"> 
                    <div class="down-content">
                      <h4><a href="{% url 'shop_app:details' pro.id %}" style="color:white;">{{ pro.name }} </a>


                        <div class="container mt-5" style="display: flex; justify-content: flex-end; align-items: flex-start; padding: 20px; height: 1px; position: relative;">
                          <form action="" method="post">
                              {% csrf_token %}
                              <input type="hidden" name="product" value="{{ pro.id }}" />
                              <button class="favorite-btn" aria-label="Add to favorites" name="like" style="background:none; border:none; padding:0; cursor:pointer;">
                                  <svg viewBox="0 0 24 24" width="1.5em" height="1.5em">
                                      <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41 0.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                                  </svg>
                              </button>
                          </form>
                      </div>
                      
                      <a>
                          <form action="" method="post">
                              {% csrf_token %}
                              <input type="hidden" name="product" value="{{ pro.id }}" />
                              <button type="submit" name="select" style="background:none; border:none; padding:0; cursor:pointer;">
                                  <svg class="shopping-btn" xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" viewBox="0 0 16 16">
                                      <path fill="currentColor" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607L1.61 2H.5a.5.5 0 0 1-.5-.5M5 12a2 2 0 1 0 0 4a2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4a2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2a1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2a1 1 0 0 1 0-2"/>
                                  </svg>
                              </button>
                          </form>
                      </a>
                      



                    </h4>
                      <strong><span class="collection">${{ pro.price }}</strong></span>
                      <span class="category">{{ pro.brand }}</span>
                      <div class="main-button">
                        <a href="{% url 'shop_app:details' pro.id %}">View Item Details</a>
                      </div>
                    </div>
                  </div>
                </form>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  
  

{% endblock %}